### ISSUE TITLE
[Bug] the format with reading concode data for code generation is wrong

### ISSUE THREAD

**Issue by WatreYoung** [NougatCA/FineTuner#12]
Thanx for the public code and wonderful work!
When i run the code generation task, i just found a problem as following:
<img width="838" alt="wrong_data" src="https://user-images.githubusercontent.com/49915237/232322652-13c6e87d-1f8a-457c-bce6-8c7b4e6e17d9.png">
So i search the origin of the split data, and then i found the code in [data.py](https://github.com/NougatCA/FineTuner/blob/main/src/data.py#L228)
```python
for idx, line in enumerate(tqdm(lines, total=len(lines), desc=f"Loading {split} data")):
        js = json.loads(line.strip())
        if args.task == "summarization":
            source = " ".join(js["code_tokens"])
            target = " ".join(js["docstring_tokens"])
        else:
            source = " ".join(js["nl"])
            target = " ".join(js["code"])
```
This part shouldn't be " ". For example. the result should be "int", but i can only get "i n t".
I think it will be ok:
```python
for idx, line in enumerate(tqdm(lines, total=len(lines), desc=f"Loading {split} data")):
        js = json.loads(line.strip())
        if args.task == "summarization":
            source = " ".join(js["code_tokens"])
            target = " ".join(js["docstring_tokens"])
        else:
            source = "".join(js["nl"])
            target = "".join(js["code"])
```

**Comment by NougatCA** [comment]
Hi @WatreYoung 

Thank you for your attention and the correction, we will fix the corresponding bug.

**Comment by WatreYoung** [comment]
ok Thanx for your work and replies!
