### ISSUE TITLE
Failed data and results links

### ISSUE THREAD

**Issue by shaoyuyoung** [NougatCA/FineTuner#13]
Hello, Changan,

It's really an interesting work.

But it seems that the data and results links are invalid. Can you check and provide them again?

Looking fowared to your reply. Thx in advance!

**Comment by NougatCA** [comment]
Hi, @shaoyuyoung,

Sorry for the late rely, I just updated the OneDrive link and added the Zenodo link, please kindly find them in the README file. Zenodo link is suggested to use due to its newer data version.

Thanks for the interests!
